### ISSUE TITLE
Daemon set deployment

### ISSUE THREAD

**Issue by jimmoods** [mko-x/docker-clamav#134]
Hi Mko 
Do you have an example of deploying this using a kubernetes daemon set? I have read through your documentation and older issues but I wasn't able to find an example.

**Comment by mko-x** [comment]
Hi @jimmoods 
Thank you for your question. So I think it depends on your setup but you can try something like this:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-clamav
  namespace: kube-system
  labels:
    k8s-app: mko-docker-clamav
spec:
  selector:
    matchLabels:
      name: docker-clamav
  template:
    metadata:
      labels:
        name: docker-clamav
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: docker-clamav
      # you may need to deploy the image somewhere available to your configuration
        image: mkodockx/docker-clamav:latest
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 300
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

This is not tested.
