### ISSUE TITLE
clamav container exist with issue on line 32 in bootstrap

### ISSUE THREAD

**Issue by kabengwa** [mko-x/docker-clamav#17]
I have set up a simple container that I want to connect to my next cloud installation(also in a container) but it keeps exiting with error,

`nextav    | /bootstrap.sh: line 32:     7 Killed                  clamd`

this is when I run docker-compose up

```
  av:
    image: mk0x/docker-clamav
    container_name: nextav
    ports:
      - 3310:3310
    networks:
      - proxy-tier
    restart: unless-stopped
```
