### ISSUE TITLE
bootstrap.sh crashes container

### ISSUE THREAD

**Issue by noone-silent** [mko-x/docker-clamav#172]
**Describe the bug**
bootstrap.sh forces container restart

**To Reproduce**
```
version: "3.8"

services:
  clamdscan:
    image: mkodockx/docker-clamav:alpine
    volumes:
      - clamd-data:/var/lib/clamav
    healthcheck:
      test: [ "CMD", "./check.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s
  volumes:
    clamd-data:
```

**Expected behavior**
Container keeps running

**Screenshots**
```
waiting for clam to update...
starting clamd...
Thu Oct 21 11:34:25 2021 -> ClamAV update process started at Thu Oct 21 11:34:25 2021
Thu Oct 21 11:34:25 2021 -> daily.cvd database is up-to-date (version: 26329, sigs: 1939370, f-level: 90, builder: raynman)
Thu Oct 21 11:34:25 2021 -> main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Thu Oct 21 11:34:25 2021 -> bytecode.cvd database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)
/bootstrap.sh: line 66:    20 Killed                  clamd
```

**Host (please complete the following information):**
 - OS: debian
 - Version buster

**Image (please complete the following information):**
 - Tag: alpine
 - Configuration: see "To Reproduce"

**Additional context**
The timeout takes some time, around 30-60 seconds
