### ISSUE TITLE
Adjust build for dockerhub to use multi-arch manifest

### ISSUE THREAD

**Issue by WhiteBahamut** [mko-x/docker-clamav#74]
**Actual:**
`docker pull mkodockx/docker-clamav:buster-slim` just has amd64 arch.

**Expected:**
`docker pull mkodockx/docker-clamav:buster-slim` should pull the correct arch for the platform I execute the command on

**Proposal:**
- have a build for each base folder (buster, stretch, main, edge)
- configure the `hooks/post_push` to execute the manifest tool (see below)

```sh
#!/bin/bash
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-args \
    --platforms linux/amd64,linux/arm/v7,linux/arm64/v8 \
    --template ${repo}docker-clamav:buster-slim-ARCHVARIANT \
    --target ${repo}docker-clamav:buster-slim
```

Not sure if this is how the hooks can work, never worked with them myself ;-) Commands for alle images can be found in `build-all.sh`

**Comment by mko-x** [comment]
I tried to manually run manifest-tool, that worked so far.

How do you recommend to configure hooks in `hooks/post_push`?

**Comment by mko-x** [comment]
You may try to install one and check the arch delivered

**Comment by WhiteBahamut** [comment]
I had a look into it and tried to figure out how it could be done. Might not be elegant, I am an Azure DevOps guy ;-)

So for each base image platform an action needs to be created, like the following:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - "debian/buster"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare for QEMU
        run: sh -c "docker run --rm --privileged multiarch/qemu-user-static:register --reset"
        
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
        uses: docker/build-push-action@v1.1.1
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: # optional
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: # optional
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: # optional
          # Docker repository to tag the image with
          repository: 
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: # optional
          # Automatically tags the built image with the git reference as per the readme
          tag_with_ref: # optional
          # Automatically tags the built image with the git short SHA as per the readme
          tag_with_sha: # optional
          # Path to the build context
          path: # optional, default is .
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: # optional
          # Sets the target stage to build
          target: # optional
          # Always attempt to pull a newer version of the image
          always_pull: # optional
          # Comma-delimited list of build-time variables
          build_args: # optional
          # Comma-delimited list of images to consider as cache sources
          cache_froms: # optional
          # Comma-delimited list of labels to add to the built image
          labels: # optional
          # Adds labels with git repository information to the built image
          add_git_labels: # optional
          # Whether to push the image
          push: # optional, default is true

      - name: Push manifest
        run: curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64 && chmod +x manifest-tool && ./manifest-tool push from-args --platforms linux/amd64,linux/arm/v7,linux/arm64/v8 --template mkodockx/docker-clamav:buster-slim-ARCHVARIANT --target ${repo}docker-clamav:buster-slim
```

Should trigger on master only if `debian/buster` changes were commited. Prepared the qemu requirements and then execute a docker build + push (should be mutliplied per `Dockerfile`) and at the end the manifest will pushed to DockerHub. Seems it could all be done within GitHub Action itself. Pay attention to the dockerx command credentials for DockerHub. Should be stored in repo Settings->Secrets.
