### ISSUE TITLE
Adding SemVer to docker images

### ISSUE THREAD

**Issue by WhiteBahamut** [mko-x/docker-clamav#80]
Currently changes to the image will always overwrite existing tags, e.g. :alpine will be overwritten by updates. If thing go wrong it is hard to recover old version. When tags have a version number in it, it is much easier to roll back as image tags (expect latest) are not overwritten.

Build sample can be found [here](https://github.com/WhiteBahamut/docker-clamav/blob/master/.github/workflows/alpine.yml). Build works btw :). `buildx` is much nicer to setup compared to the manifest-tool apporach I used before

- [ ] Setup for alpine
- [ ] Setup for alpine-edge
- [ ] Setup for debian-buster
- [ ] Setup for debian-stretch

_Following @shaunakv1 suggestion in https://github.com/mko-x/docker-clamav/issues/78#issuecomment-716691956_

**Comment by WhiteBahamut** [comment]
I've added actions for alle image variants. wont make a PR for it right now. If you want to can just copy and paste ;) Still want to adjust some things.
But you need to add two secrets to this Repo
- DOCKERHUBUSERNAME 
- DOCKERHUBTOKEN 

works for my [docker hub](https://hub.docker.com/r/whitebahamut/docker-clamav/tags?page=1&ordering=last_updated)

**Comment by mko-x** [comment]
Thank you very much @WhiteBahamut  👍 
I will do so. Looking forward to your PR (:

**Comment by WhiteBahamut** [comment]
I played with the actions a bit. There are two options of getting version (well there are more, but 2 I like ;-))
1) Build new images only if changes were made to them, e.g. commit in `/alpine/main` would only build only a new `:alpine`
2) Build new images on any change in master, e.g. commit in `/alpine/main` would only build all tags

Personally I like 1) more. But it would still need some work (or might even impossible). I use the GitVersion and I would need to figure out how to influence the semver calculation only to concider certain git-tags (e.g. `alpine-1.0.0`).
The option 2) seems to be more or less straight forward. Just build all the images, upload them and apply a git tag.

Any preference?

**Comment by mko-x** [comment]
I prefer option 1, option 2 would be a workaround
Should be possible with actions, shouldn't it?

**Comment by WhiteBahamut** [comment]
Will do some research, but does not look good for option 1 right now. Maybe there are other version action then GitVersion (which I use right now). Still might take some time

**Comment by mko-x** [comment]
Any news on this?

**Comment by WhiteBahamut** [comment]
Oh sorry... was totally into other things and mostly will be distracted. I'll just post a potential start for an action

**I have not tested the following action file**. But it should build and push the images. But it will build all, no matter on which sub path the commit was. E.g. build alpine if commit was in debian.
```yaml
name: build-and-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: ["alpine", "alpine-edge", "buster", "strech"]
        include:
          - tag: "alpine"
            path: "./alpine/main"
          - tag:  "alpine-edge"
            path: "./alpine/edge"
         - tag: "buster"
           path: "./debian/buster"
         - tag: "strech"
           path: "./debian/strech"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: '5.x'
        
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.4
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}
        
      - name: Build and Push with version
        uses: docker/build-push-action@v2.0.1
        with:
          tags: |
            mkodockx/docker-clamav:${{ steps.gitversion.outputs.semVer }}-${{ matrix.tag }}         
            mkodockx/docker-clamav:${{ matrix.tag }} 
          file: ${{ matrix.path }}/Dockerfile
          context: ${{ matrix.path }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
```
